export const CREATE_COURSE = "CREATE_COURSE";
export const USER_SESSION_VALID = "USER_SESSION_VALID";
export const USER_SESSION_INVALID = "USER_SESSION_INVALID";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAILED = "USER_LOGIN_FILED";
export const USER_LOGOUT = "USER_LOGOUT";
export const CREATE_TOKEN_REFRESH = "CREATE_TOKEN_REFRESH";



// export const SIGNIN_FAILURE = 'SIGNIN_FAILURE';
// export const AUTH_USER = 'AUTH_USER';
// export const UNAUTH_USER = 'UNAUTH_USER';
export const PROJECTS_FETCH = 'PROJECTS_FETCH';
export const PROJECTS_REQUEST = 'PROJECTS_REQUEST';
export const PROJECTS_SUCCESS = 'PROJECTS_SUCCESS';
export const PROJECTS_FAILURE = 'PROJECTS_FAILURE';
export const PROJECTS_SELECTED = 'PROJECTS_SELECTED';
export const PROVISIONE_PRODUCT_SELECTED = 'PROVISIONE_PRODUCT_SELECTED';
export const PROVISIONE_PRODUCT_SUCCESS = 'PROVISIONE_PRODUCT_SUCCESS';
export const GETALL_PROVISIONEDPRODUCTDETAILS_SUCCESS = 'GETALL_PROVISIONEDPRODUCTDETAILS_SUCCESS';
export const SERVICEACTION_EXECUTE_STATUS = 'SERVICEACTION_EXECUTE_STATUS';

export const PROJECT_NOT_SELECTED = 'PROJECT_NOT_SELECTED';
export const GETALL_REQUEST = 'GETALL_REQUEST';
export const GETALL_STATS_FETCH = 'GETALL_STATS_FETCH';
export const GETALL_STATS_SUCCESS = 'GETALL_STATS_SUCCESS';
export const GETALL_RECENTLYUSED_FETCH = 'GETALL_RECENTLYUSED_FETCH';
export const GETALL_RECENTLYUSED_SUCCESS = 'GETALL_RECENTLYUSED_SUCCESS';
export const GETALL_PROVISIONEDPRODUCTS_FETCH = 'GETALL_PROVISIONEDPRODUCTS_FETCH';
export const GETALL_PROVISIONEDPRODUCTS_SUCCESS = 'GETALL_PROVISIONEDPRODUCTS_SUCCESS';
export const GETALL_PRODUCTSCATALOG_FETCH = 'GETALL_PRODUCTSCATALOG_FETCH';
export const GETALL_PRODUCTSCATALOG_SUCCESS = 'GETALL_PRODUCTSCATALOG_SUCCESS';
export const BANNER = 'BANNER';
export const CHANGE_VIEW = 'CHANGE_VIEW';